version: '2'

services:
  devenv:
    build:
      context: ..
      dockerfile: bin/Dockerfile
    image: malikoth/devenv
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\:/c
      - D:\:/d
      - E:\:/e
      - F:\:/f